### ISSUE TITLE
Latest update causes runtime errors on image save

### ISSUE THREAD

**Issue by vladmandic** [ArtVentureX/sd-webui-agent-scheduler#170]
commit https://github.com/ArtVentureX/sd-webui-agent-scheduler/commit/c32395e42a6095db79ad6715e28d578984a6c89f
creates an error:

```log
│ /home/vlado/dev/sdnext-master/extensions-builtin/sd-webui-agent-scheduler/agent_scheduler/task_runner.py:524 in __on_image_saved                                                                     │
│                                                                                                                                                                                                      │
│   523 │   def __on_image_saved(self, data: script_callbacks.ImageSaveParams):                                                                                                                        │
│ ❱ 524 │   │   if data.filename.startswith(data.p.outpath_grids):                                                                                                                                     │
│   525 │   │   │   self.__saved_images_path.insert(0, data.filename)
```

note that there is no `data.p.outpath_grids`, there is `data.outpath_grids` - `ImageSaveParams` object does not have `p` as its member!
and even that is not guaranteed to exist, so access should be optional.

@tungnguyensipher

**Comment by artventuredev** [comment]
Understood. I saw `p` in `ImageSaveParams` and assumed it was still in use, similar to A1111. I've just pushed a fix for this issue.

<img width="505" alt="image" src="https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/133728487/1c74c669-6740-479e-abb9-27461726c6c4">
<img width="591" alt="image" src="https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/133728487/75d8a409-1ac6-4571-a2fc-8507bf777043">

Additionally, I observed that `window.submit` has been changed to `window.submit_txt2img`, and I've implemented a fix for this as well.

**Comment by vladmandic** [comment]
re: submit, old one still exists, so you don't need special handler sdnext/a1111.

`const submit = submit_txt2img;`
