### ISSUE TITLE
Thumbnails, info and action buttons error on display

### ISSUE THREAD

**Issue by Pixelmunky** [ArtVentureX/sd-webui-agent-scheduler#39]
Hey there, first of all... thanks for creating this extension, it saves me so much time!

I am however experiencing an issue where the thumbnails, info and actions are not displayed. I simply see a red error message (see attached screen shot).

For clarity, the images are generated and can be located in the usual txt2img directory, they're just not being displayed in the UI. If I run a generation as normal (non scheduled), the thumbnails display as expected.

I have fully re-installed A1111, and am running it with no other extensions as of today. The issue persists if I use the Scheduler in a new tab, or if I append it to the main text2img UI.

![no-thumbnails](https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/4622266/15b42cfb-d845-42b3-b020-ff5e3b397c5d)

**Comment by artventuredev** [comment]
Please provide the full SD web ui logs for debugging. The logs are in the command prompt window that opened when you run the `webui.bat`.

And if possible, please attach the `task_scheduler.sqlite3` file in the extension folder:
```
C:\path\to\stable-diffusion-webui\extensions\sd-task-scheduler\task_scheduler.sqlite3
```

**Comment by Pixelmunky** [comment]
Sure, here you go:

[task_scheduler-logs.zip](https://github.com/ArtVentureX/sd-webui-agent-scheduler/files/11848737/task_scheduler-logs.zip)

**Comment by Slowbud1** [comment]
I've the same issue and this weird path in the Log:
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Temp\\gradio\\tmp7gb02596.png'

**Comment by artventuredev** [comment]
Look like this is a gradio issue https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11040

Please try create the `gradio` folder at the `c:\Temp` (or whatever folder in the errror) and the issue should be fixed.

**Comment by SirMoogle** [comment]
> Look like this is a gradio issue [AUTOMATIC1111/stable-diffusion-webui#11040](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11040)
> 
> Please try create the `gradio` folder at the `c:\Temp` (or whatever folder in the errror) and the issue should be fixed.

I've tried the above and it seems to be a temporary fix; turning off the device usually removes the folder and you'll have to do it all over again. I discovered what appeared to be [a more permanent solution](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11040#issuecomment-1604990473).

**Comment by Pixelmunky** [comment]
Installing Gradio in the root directory doesn't solve the OP problem, just for anyone else reading this.

**Comment by Pixelmunky** [comment]
Upon further review... while it seemed like it fixed the issue, it's actually only showing the single grid image thumbnail, rather than the individual images generated, meaning I can't select the image and send to img2img or something. I still have to navigate to the text2img directory to get the seed for the image I want. I can't see any additional errors in the log.

**Comment by artventuredev** [comment]
@Pixelmunky, I noticed that the issue occurs when the extension UI is rendered below the main UI. If that's the case for you, I'd suggest updating the extension and giving it another shot.

**Comment by Pixelmunky** [comment]
Ah thanks! it's working now after the update.
