### ISSUE TITLE
Can't work with "sd-webui-prompt-all-in-one" extension

### ISSUE THREAD

**Issue by liuycy** [ArtVentureX/sd-webui-agent-scheduler#78]
When this extension enabled with [sd-webui-prompt-all-in-one](https://github.com/Physton/sd-webui-prompt-all-in-one), it doesn't work. I clicked the "Enqueue" button but nothing happened.

However, when I disabed "sd-webui-prompt-all-in-one" extension, it works. I clicked the "Enqueue" button, I can see the task in the Agent Scheduler Tab.

**Comment by artventuredev** [comment]
Please update the extension and try again, the issue should be fixed.

**Comment by liuycy** [comment]
> 

I just updated my extension and took it a try, but it still doesn't work. I clicked the button but nothing happened.

Here's more info about my enviorment:
python version: 3.10.6
webui version: 1.4.0
I'm Launching Web UI with arguments: --skip-torch-cuda-test --upcast-sampling --no-half-vae --use-cpu interrogate
on my M1 Mac

**Comment by tungnguyensipher** [comment]
Please post your SD console log for futher debugging.

**Comment by liuycy** [comment]
> Please post your SD console log for futher debugging.

> Please update the extension and try again, the issue should be fixed.

I just restarted my WebUI and it works. Thanks for your help.
